"""Write the QC head v2 report and model card from ``qc_esc50_v2_results.json``.

Called by ``python ml/train/esc50_qc_mix.py report``. Every number printed here
is read from the results file.
"""

from __future__ import annotations

import json

import esc50_qc_mix as mx
import evalkit as ek
from esc50_qc import CATEGORIES, CATEGORY_KIND, CATEGORY_MAP, CONTAMINATION, REPO

REPORT = REPO / "ml" / "reports" / "qc_esc50_v2.md"
CARD = REPO / "docs" / "model-cards" / "qc-soundscape-v2.md"
SNR_KEYS = [("+10", "+10 dB"), ("+0", "0 dB"), ("-10", "-10 dB")]


def ci(t) -> str:
    return ek.fmt_ci(t)


def pc(t) -> str:
    """Rate triple [p, lo, hi] as percent."""
    return f"{100 * t[0]:.0f}% ({100 * t[1]:.0f} to {100 * t[2]:.0f})"


def pts(t) -> str:
    """Difference triple in percentage points."""
    return f"{100 * t[0]:+.0f} points ({100 * t[1]:+.0f} to {100 * t[2]:+.0f})"


def summary(res: dict) -> list[str]:
    cl = res["clean"]
    d = cl["diff_v2_minus_v1"]
    E = res["mixtures_eval"]["backend"]
    ff = res["clean_bio_false_contamination_flag"]["backend"]
    out = [
        f"Decision: v2 {'meets' if res['decision']['ship'] else 'does not meet'} the ship criteria written down before the results (table below)"
        + (
            ", so it is exported and becomes the backend default."
            if res["decision"]["ship"] and "export" in res
            else ", so v1 stays the default."
            if not res["decision"]["ship"]
            else "."
        ),
        f"Clean ESC-50 test folds: macro AP v1 {ci(cl['v1_f1']['macro']['ap'])}, v2 {ci(cl['v2_f1']['macro']['ap'])}; difference {ci(d['macro_ap'])}. Macro F1 v1 {ci(cl['v1_f1']['macro']['f1'])}, v2 {ci(cl['v2_f1']['macro']['f1'])}; difference {ci(d['macro_f1'])}.",
        "Held-out mixtures (a bird, frog or insect clip plus one of six contaminants, backend warning rule): the added contaminant is flagged at "
        + ", ".join(
            f"{lab} by v1 in {pc(E['v1'][f'all@{k}']['detected'])} and v2 in {pc(E['v2'][f'all@{k}']['detected'])}"
            for k, lab in SNR_KEYS
        )
        + " of mixtures.",
        "Gain in detection (v2 minus v1, same mixtures): "
        + ", ".join(f"{lab} {pts(E['gain_v2_minus_v1'][f'all@{k}'])}" for k, lab in SNR_KEYS)
        + ".",
        f"False contamination warnings on clean bird, frog and insect test clips (backend rule): v1 {pc(ff['v1'])}, v2 {pc(ff['v2'])}; difference {pts(ff['diff'])}.",
        "The mixtures are synthetic: two curated ESC-50 clips added together. They are not field recordings, and these are not field accuracy numbers.",
    ]
    if "_v2a" in res:
        out.insert(
            1,
            "A first attempt (v2a, union labels, equal weights) flagged far more contaminants under calls but lost clean accuracy and failed the criteria; v2 (v2b) keeps mixture training only where it does not cost clean accuracy. v2b was designed after seeing v2a's results (see the honesty note).",
        )
    return out


def criteria_table(res: dict) -> list[str]:
    c = res["config"]["ship_criteria"]
    ch = res["decision"]["checks"]
    rows = [
        (
            "clean_macro_ap_diff_ci_low",
            f"Lower end of the 95% CI of clean macro AP difference (v2 minus v1) is at least {c['clean_macro_ap_diff_ci_low_min']}",
        ),
        (
            "clean_macro_ap_diff_point",
            f"Clean macro AP difference is at least {c['clean_macro_ap_diff_point_min']}",
        ),
        (
            "clean_macro_f1_diff_point",
            f"Clean macro F1 difference is at least {c['clean_macro_f1_diff_point_min']}",
        ),
        ("mixture_gain_0dB_ci_low", "Detection gain at 0 dB: lower end of 95% CI above 0"),
        ("mixture_gain_minus10dB_ci_low", "Detection gain at -10 dB: lower end of 95% CI above 0"),
        (
            "clean_bio_false_flag_increase",
            f"Increase in false contamination warnings on clean bird, frog and insect clips is at most {c['clean_bio_false_flag_increase_max_backend_rule']}",
        ),
    ]
    L = ["| Criterion | Value | Pass |", "|---|---|---|"]
    for key, text in rows:
        L.append(f"| {text} | {ch[key]['value']:+.3f} | {'yes' if ch[key]['pass'] else 'no'} |")
    return L


def write_report(res: dict) -> None:
    cfg = res["config"]
    cl = res["clean"]
    L: list[str] = []
    a = L.append
    a("# Soundscape QC head v2 (mixture training) on ESC-50: evaluation report")
    a("")
    a(
        "Generated by `ml/train/esc50_qc_mix.py` (text by `ml/train/esc50_qc_mix_report.py`). Every number comes from `ml/reports/qc_esc50_v2_results.json` (v2, called v2b below) or `ml/reports/qc_esc50_v2a_results.json` (the first attempt), which also store the settings. v1 is described in `ml/reports/qc_esc50_v1.md`."
    )
    a("")
    a(
        "**The mixtures in this report are synthetic.** Each one adds two curated ESC-50 clips digitally. They are not field recordings; real overlap has distance, reverberation and recorder noise that these mixtures do not have."
    )
    a("")
    a("## Summary")
    a("")
    for s in summary(res):
        a(f"* {s}")
    a("")
    a("## Ship criteria (set before the results)")
    a("")
    a(
        "The criteria were written into `esc50_qc_mix.py` before v2 was evaluated. Detection gains use the backend warning rule (score above max(0.5, threshold))."
    )
    a("")
    L.extend(criteria_table(res))
    a("")
    a(f"Result: **{'ship' if res['decision']['ship'] else 'do not ship'}**.")
    a("")
    a("## How v2 was built (two attempts)")
    a("")
    n = cfg["n_mixtures"]
    a(
        f"* **Mixtures, built inside each ESC-50 fold.** Both clips of a mixture come from the same official fold, so no source recording is shared between training and test mixtures (checked in code). For each fold: {cfg['n_train_mix_per_fold']} training-pool mixtures ({n['train_pool']} in total) and an evaluation set ({n['eval']} in total), embedded once with BirdNET exactly like v1 (3 s windows, 1 s hop, mean and max pooling; sha256 `{cfg['birdnet_sha256'][:16]}...`)."
    )
    a(
        f"* **Training pool.** Base clip category drawn with weights {', '.join(f'{k} {v}' for k, v in cfg['mix_bases'].items())}; contaminant category drawn uniformly from {', '.join(cfg['mix_contaminants'])} (never the base's own category); a random clip of each; signal-to-noise ratio uniform in {cfg['train_snr_range_db'][0]:+.0f} to {cfg['train_snr_range_db'][1]:+.0f} dB."
    )
    a(
        f"* **Evaluation set.** Every bird, frog and insect clip of the fold, each mixed with {cfg['eval_contaminants_per_clip_and_snr']} contaminant categories (rotating over the six) at each of +10, 0 and -10 dB: 100 mixtures per contaminant and ratio. These mixtures are never used for training or for any choice."
    )
    a(
        f"* **Signal-to-noise ratio.** {cfg['snr_definition'][0].upper() + cfg['snr_definition'][1:]}. A negative value means the contaminant is louder."
    )
    a("")
    v2a = res.get("_v2a")
    if v2a:
        d = v2a["clean"]["diff_v2_minus_v1"]
        g = v2a["mixtures_eval"]["backend"]["gain_v2_minus_v1"]
        ffa = v2a["clean_bio_false_contamination_flag"]["backend"]["diff"]
        a(
            "**Attempt 1 (v2a): union labels, clean and mixtures weighted equally.** Labels were the union of both clips' categories at any ratio, and one C (chosen from "
            + f"{v2a['config']['c_grid']}) was shared by all categories. On held-out mixtures it flagged the contaminant far more often than v1 (gain "
            + ", ".join(f"{lab} {pts(g[f'all@{k}'])}" for k, lab in SNR_KEYS)
            + f"), but it got clearly worse on clean clips: macro AP difference {ci(d['macro_ap'])}, macro F1 difference {ci(d['macro_f1'])}, false contamination warnings on clean bird, frog and insect clips {pts(ffa)}. It failed the pre-registered criteria "
            + f"({sum(not c['pass'] for c in v2a['decision']['checks'].values())} of {len(v2a['decision']['checks'])} checks failed) and was not shipped. Its full results are in `qc_esc50_v2a_results.json`."
        )
        a("")
    dg = res.get("design_diagnostic_v2b")
    if dg:
        a(
            "**Diagnosis on training data only.** To choose a fix without touching outer test fold 1, we trained on three of folds 2 to 5 and validated on the fourth (fold 2, then fold 3), comparing recipes at two C values. Clean and mixture macro AP on the validation fold (mixtures scored with SNR up to +10 dB):"
        )
        a("")
        a("| Validation fold | Recipe | C | Clean macro AP | Mixture macro AP |")
        a("|---|---|---|---|---|")
        for r in dg["rows"]:
            a(
                f"| {r['val_fold']} | {r['recipe']} | {r['C']} | {r['clean_macro_ap']:.3f} | {r['mixture_macro_ap']:.3f} |"
            )
        a("")
        a(
            "Every mixture recipe cost some clean AP; audibility-gated labels and a lower mixture weight cost the least, and smaller C helped. A single linear head cannot fully serve both clean clips and mixtures, so the fix below chooses, per category, whether mixture training is worth its clean cost."
        )
        a("")
    a(
        f"**Attempt 2 (v2b, the v2 that is evaluated below).** (1) Audibility-gated training labels: the contaminant counts as present only if it is at most {cfg['gate_db'][0]:.0f} dB below the base, and the base only if it is at most {-cfg['gate_db'][1]:.0f} dB below the contaminant. (2) For each category separately, the training recipe (mixture weight "
        + ", ".join(f"{w}" for _, w in cfg["v2b_recipes"])
        + f", where 0 means clean clips only) and C (from {cfg['c_grid']}) are chosen by leave-one-fold-out inside the training folds: a (recipe, C) pair is allowed only if its clean AP is within {cfg['v2b_clean_tolerance']} of the best clean-only AP for that category, and among allowed pairs the best AP on clean clips and mixtures together wins. (3) Platt scaling and thresholds are fit on the out-of-fold predictions for clean clips and gated-label mixtures. (4) The per-category models are merged into one standardization, so the file format is exactly v1's."
    )
    a("")
    a(
        "**Honesty note.** v2b was designed after we had seen v2a's test-fold results, and the diagnosis above used folds that are test folds in other rotations. Its recipe candidates are therefore not a fully blind choice, and its test numbers may be slightly optimistic. The ship criteria were not changed."
    )
    a("")
    choices = {}
    for f in res["folds"].values():
        for c, v in f["inner_macro_ap"].items():
            choices.setdefault(c, []).append(v["recipe"].replace("gated_", "") + f"/C={v['C']}")
    a("Recipe and C chosen per category in each outer fold (recipe name, then C):")
    a("")
    a("| Category | Fold 1 | Fold 2 | Fold 3 | Fold 4 | Fold 5 |")
    a("|---|---|---|---|---|---|")
    for c in CATEGORIES:
        a(f"| `{c}` | " + " | ".join(choices.get(c, [])) + " |")
    a("")
    a(
        "* **Protocol.** For test fold k, everything above runs on the clean clips and training-pool mixtures of the other four folds only. The model is then tested on fold k's clean clips, its training-pool mixtures and its evaluation mixtures. v1 numbers come from the saved v1 fold models on the same data, so comparisons are paired."
    )
    a(
        f"* **Uncertainty.** Clean clips: cluster bootstrap over source recordings, as in v1. Mixtures: a two-way ('pigeonhole') bootstrap that resamples base-clip sources and contaminant-clip sources independently, because each clip appears in several mixtures. {cfg['n_boot']} resamples; 95% percentile intervals."
    )
    a("")
    if not res["decision"]["ship"]:
        a("## Why v2 was not shipped")
        a("")
        v1m, v2m = cl["v1_f1"]["macro"], cl["v2_f1"]["macro"]
        b1, b2 = cl["v1_backend"]["macro"], cl["v2_backend"]["macro"]
        failed = [k for k, v in res["decision"]["checks"].items() if not v["pass"]]
        a(
            f"Failed check(s): {', '.join(failed)}. v2's clean ranking is as good as v1's (macro AP difference {ci(cl['diff_v2_minus_v1']['macro_ap'])}), but its own F1 thresholds flag too much on clean clips: macro precision falls from {ci(v1m['precision'])} to {ci(v2m['precision'])} while recall rises from {ci(v1m['recall'])} to {ci(v2m['recall'])}. Clips flagged per category at those thresholds (v1 then v2): "
            + ", ".join(
                f"{c} {cl['v1_f1']['per_class'][c]['n_flagged']} then {cl['v2_f1']['per_class'][c]['n_flagged']}"
                for c in CATEGORIES
            )
            + "."
        )
        a("")
        a(
            f"The likely cause is a base-rate shift: Platt scaling and thresholds were fit on clean clips and mixtures together, where contamination is far more common than in the clean set, so v2's probabilities run high on clean clips (expected calibration error {cl['ece']['v1']:.3f} for v1, {cl['ece']['v2']:.3f} for v2). Under the backend's own warning rule (score above max(0.5, threshold)) the clean macro F1 is similar: v1 {ci(b1['f1'])}, v2 {ci(b2['f1'])} (precision {ci(b1['precision'])} vs {ci(b2['precision'])}, recall {ci(b1['recall'])} vs {ci(b2['recall'])})."
        )
        a("")
        a(
            "We did not change the criterion after seeing this. The pre-registered check uses each model's own F1 thresholds, and v2 fails it. v1 stays the default and no v2 file is written to the backend. A sensible next step is to fit v2's calibration and thresholds on clean out-of-fold predictions (or to reweight to a field base rate), and then to confirm on data not used here, ideally the field gold set (`ml/eval/gold_benchmark.py`). Re-testing on these ESC-50 folds after a third round of changes would make the estimate too optimistic."
        )
        a("")
    a("## (a) Clean ESC-50 test folds")
    a("")
    v1, v2 = cl["v1_f1"], cl["v2_f1"]
    a("| Category | AP v1 | AP v2 | AP difference | F1 v1 | F1 v2 |")
    a("|---|---|---|---|---|---|")
    for c in CATEGORIES:
        a(
            f"| `{c}` | {ci(v1['per_class'][c]['ap'])} | {ci(v2['per_class'][c]['ap'])} | {ci(cl['diff_v2_minus_v1']['ap_per_category'][c])} | {ci(v1['per_class'][c]['f1'])} | {ci(v2['per_class'][c]['f1'])} |"
        )
    a(
        f"| **macro** | {ci(v1['macro']['ap'])} | {ci(v2['macro']['ap'])} | {ci(cl['diff_v2_minus_v1']['macro_ap'])} | {ci(v1['macro']['f1'])} | {ci(v2['macro']['f1'])} |"
    )
    a(
        f"| **micro** | {ci(v1['micro']['ap'])} | {ci(v2['micro']['ap'])} | | {ci(v1['micro']['f1'])} | {ci(v2['micro']['f1'])} |"
    )
    a("")
    b1, b2 = cl["v1_backend"]["macro"], cl["v2_backend"]["macro"]
    a(
        f"At the backend warning rule: macro precision v1 {ci(b1['precision'])}, v2 {ci(b2['precision'])}; macro recall v1 {ci(b1['recall'])}, v2 {ci(b2['recall'])}. Expected calibration error (all category-clip pairs): v1 {cl['ece']['v1']:.3f}, v2 {cl['ece']['v2']:.3f}."
    )
    a("")
    ffr = res["clean_bio_false_contamination_flag"]
    a(
        f"False contamination flags on the {ffr['backend']['n']} clean bird, frog and insect test clips: F1 thresholds v1 {pc(ffr['f1']['v1'])}, v2 {pc(ffr['f1']['v2'])}; backend rule v1 {pc(ffr['backend']['v1'])}, v2 {pc(ffr['backend']['v2'])}."
    )
    a("")
    a("![Clean AP v1 vs v2](figures/qc_v2_clean_ap.png)")
    a("")
    a("## (b) Held-out mixtures at fixed signal-to-noise ratios")
    a("")
    E = res["mixtures_eval"]["backend"]
    a(
        "Share of evaluation mixtures where the added contaminant is flagged (backend warning rule), 100 mixtures per cell:"
    )
    a("")
    a("| Contaminant | SNR | v1 | v2 | Gain (v2 minus v1) |")
    a("|---|---|---|---|---|")
    for c in mx.MIX_CONTAMINANTS + ["all"]:
        for k, lab in SNR_KEYS:
            key = f"{c}@{k}"
            name = "all six" if c == "all" else f"`{c}`"
            a(
                f"| {name} | {lab} | {pc(E['v1'][key]['detected'])} | {pc(E['v2'][key]['detected'])} | {pts(E['gain_v2_minus_v1'][key])} |"
            )
    a("")
    sig = {
        k: [c for c in mx.MIX_CONTAMINANTS if E["gain_v2_minus_v1"][f"{c}@{k}"][1] > 0]
        for k, _ in SNR_KEYS
    }
    a(
        "Contaminants whose detection gain has a 95% CI above zero: "
        + "; ".join(f"{lab}: {', '.join(sig[k]) or 'none'}" for k, lab in SNR_KEYS)
        + "."
    )
    a("")
    a("Side effects on the same mixtures (all six contaminants pooled):")
    a("")
    a(
        "| SNR | Bird / frog / insect still flagged, v1 | v2 | Another contamination category also flagged, v1 | v2 |"
    )
    a("|---|---|---|---|---|")
    for k, lab in SNR_KEYS:
        a(
            f"| {lab} | {pc(E['v1'][f'all@{k}']['base_still_flagged'])} | {pc(E['v2'][f'all@{k}']['base_still_flagged'])} | {pc(E['v1'][f'all@{k}']['other_contamination_flag'])} | {pc(E['v2'][f'all@{k}']['other_contamination_flag'])} |"
        )
    a("")
    Ef = res["mixtures_eval"]["f1"]
    a(
        "With the F1 thresholds instead of the backend rule, detection (all six pooled) is: "
        + ", ".join(
            f"{lab} v1 {pc(Ef['v1'][f'all@{k}']['detected'])}, v2 {pc(Ef['v2'][f'all@{k}']['detected'])}"
            for k, lab in SNR_KEYS
        )
        + "."
    )
    a("")
    a("![Detection per contaminant](figures/qc_v2_mixture_detection.png)")
    a("")
    a("![Pooled mixture summary](figures/qc_v2_mixture_summary.png)")
    a("")
    R = res["mixtures_random_snr_ap"]
    a(
        f"Multi-label average precision on the test folds' training-pool mixtures ({R['n']} mixtures, random ratios, bases include domestic animals and human sounds; bootstrap over base-clip sources): macro AP v1 {ci(R['v1_macro_ap'])}, v2 {ci(R['v2_macro_ap'])}. Per category (v1 / v2): "
        + ", ".join(
            f"{c} {v['v1']:.2f} / {v['v2']:.2f}"
            for c, v in R["per_category_ap"].items()
            if v["n_pos"]
        )
        + "."
    )
    a("")
    Rg = res.get("mixtures_random_snr_ap_gated_labels")
    if Rg:
        a(
            f"Scored with audibility-gated labels instead: macro AP v1 {ci(Rg['v1_macro_ap'])}, v2 {ci(Rg['v2_macro_ap'])}."
        )
        a("")
    bn = res["birdnet_taxon_rate_at_0.6_eval_mixtures"]
    a(
        "For context, BirdNET's matching-taxon label reaches 0.6 on the evaluation mixtures in: "
        + "; ".join(
            f"{lab}: bird {100 * bn[k]['bird']:.0f}%, frog {100 * bn[k]['frog']:.0f}%, insect {100 * bn[k]['insect']:.0f}%"
            for k, lab in SNR_KEYS
        )
        + "."
    )
    a("")
    a("## Long recordings (synthetic, clean windows)")
    a("")
    a(
        "Same check as v1 (30 s and 60 s recordings built from test-fold clips; bird, insect and frog background; backend rule). Detection is the mean over the 7 contamination categories."
    )
    a("")
    a("| Model | Pooling | Detected, 1 of 6 clips | 3 of 6 | 6 of 6 | False warning, 30 s | 60 s |")
    a("|---|---|---|---|---|---|---|")
    for ver in ("v1", "v2"):
        rr = res[f"pooling_check_{ver}"]["backgrounds"]["biophony"]["rules"]["backend"]
        for md in ("whole", "segment_max", "segment_top25"):
            d = rr["detection_rate"]
            f = rr["false_flag_rate"]
            a(
                f"| {ver} | `{md}` | {100 * d['1']['mean_over_categories'][md]:.0f}% | {100 * d['3']['mean_over_categories'][md]:.0f}% | {100 * d['6']['mean_over_categories'][md]:.0f}% | {100 * f['6'][md]['any_contamination']:.0f}% | {100 * f['12'][md]['any_contamination']:.0f}% |"
            )
    a("")
    a(
        "The shipped head (v1) uses `segment_top25` (a category must be present in about a quarter of the 6 s segments); a v2 file would use the same rule."
    )
    a("")
    sm = res.get("fixture_smoke")
    if sm:
        a("## One real field soundscape (anecdote)")
        a("")
        a(f"`{sm['file']}` (30 s dawn chorus, {sm['n_windows']} windows). Recording-level scores:")
        a("")
        a("| Model | bird | insect | highest contamination category | Backend warnings |")
        a("|---|---|---|---|---|")
        for ver in ("v1", "v2"):
            pr = sm[ver]["probabilities"]
            worst = max(CONTAMINATION, key=lambda c, pr=pr: pr[c])
            a(
                f"| {ver} | {pr['bird']:.3f} | {pr['insect']:.3f} | {worst} {pr[worst]:.3f} | {', '.join(sm[ver]['backend_warnings']) or 'none'} |"
            )
        a("")
    exp = res.get("export")
    if exp:
        a("## Exported model")
        a("")
        pcc = exp["per_category_choice"]
        a(
            f"`{exp['artifact']}` ({exp['artifact_bytes']} bytes, sha256 `{exp['artifact_sha256'][:16]}...`), same file format as v1, trained on all {exp['n_training_rows']['clean']} clean clips plus {exp['n_training_rows']['mixtures']} training-pool mixtures (the evaluation mixtures are not used), with the v2b procedure run on all 5 folds. Chosen per category: "
            + ", ".join(
                f"{c} {v['recipe'].replace('gated_', '')} C={v['C']}" for c, v in pcc.items()
            )
            + f'. The backend loader reproduces the training-side probabilities to within {exp["backend_parity_max_abs_diff"]:.1e}. `thicket.models.qc_head.load_default()` now returns v2; v1 stays available as `load_version("qc_head_v1")`.'
        )
        a("")
        a("| Category | Threshold (F1) | Threshold (precision >= 0.9) |")
        a("|---|---|---|")
        for c in CATEGORIES:
            a(f"| `{c}` | {exp['thresholds_f1'][c]:.3f} | {exp['thresholds_p90'][c]:.3f} |")
        a("")
    a("## Limitations")
    a("")
    for s in limits(res):
        a(f"* {s}")
    a("")
    a("## Reproduce")
    a("")
    a("```")
    a(
        "python ml/train/esc50_qc.py features --data /home/claude/data/esc50   # v1 features, if not cached"
    )
    a(
        "python ml/train/esc50_qc.py evaluate --data /home/claude/data/esc50   # v1 fold models (paired baseline)"
    )
    a("python ml/train/esc50_qc_mix.py all --data /home/claude/data/esc50")
    a(
        "# = mixfeatures, evaluate --variant v2a, diagnose, evaluate --variant v2b, export (only if the criteria pass), smoke, report"
    )
    a("```")
    a("")
    a(
        f"Mixture embedding took {cfg['mixfeature_seconds'] / 60:.1f} min and evaluation {res['seconds'] / 60:.1f} min on 2 vCPU. Seed {cfg['seed']}."
    )
    a("")
    REPORT.write_text("\n".join(L))


def limits(res: dict) -> list[str]:
    E = res["mixtures_eval"]["backend"]["v2"]
    weakest = min(mx.MIX_CONTAMINANTS, key=lambda c: E[f"{c}@-10"]["detected"][0])
    return [
        "All mixtures are synthetic sums of two close-range ESC-50 clips. Real overlap in the field (distance, reverberation, several sources, recorder noise) is not represented, so these gains may not carry over in full.",
        "Training and test mixtures reuse the same few clips many times (for example 8 rain clips per fold); the two-way bootstrap accounts for this, but a small clip pool still limits how general the result is.",
        f"Detection still depends strongly on the ratio and the contaminant: the weakest case for v2 is `{weakest}` at -10 dB ({pc(E[f'{weakest}@-10']['detected'])}).",
        f"v2b's training labels use an audibility gate (+{res['config']['gate_db'][0]:.0f} / {res['config']['gate_db'][1]:.0f} dB) set by judgment, not by listening tests; real listeners may hear or miss quiet sources differently.",
        "Everything in v1's limitations still applies: ESC-50 is not field audio, `bird`, `insect` and `frog` scores are not validated for users, short bursts are not flagged at the recording level, and no field validation has been done.",
    ]


def write_card(res: dict) -> None:
    exp = res["export"]
    cl = res["clean"]["v2_f1"]
    E = res["mixtures_eval"]["backend"]
    ff = res["clean_bio_false_contamination_flag"]["backend"]
    pcb = res["pooling_check_v2"]["backgrounds"]["biophony"]["rules"]["backend"]
    L: list[str] = []
    a = L.append
    a("# Model card: Thicket soundscape QC head v2")
    a("")
    a(
        f"Version `qc_head_v2`, created {exp['created']}. Supersedes `qc_head_v1` (card: `docs/model-cards/qc-soundscape-v1.md`), which stays loadable by name. Status: experimental audio quality aid that produces warnings only; not validated on field recordings. Full evaluation: `ml/reports/qc_esc50_v2.md`."
    )
    a("")
    a("## What it is")
    a("")
    a(
        "The same small linear model on BirdNET v2.4 embeddings as v1, with the same 10 categories, pooling and file format. The change is the training data: for each category, training may also use synthetic mixtures of ESC-50 clips (a bird, frog, insect, domestic animal or human sound plus a contaminant, with audibility-gated labels), when cross-validation on training folds shows this does not cost more than 0.01 clean average precision for that category. The aim is to notice a contaminant that sits under another sound."
    )
    pcc = exp["per_category_choice"]
    a("")
    a(
        "Training recipe chosen per category for the shipped file (mixture weight 0 means clean clips only): "
        + ", ".join(
            f"`{c}` {dict(res['config']['v2b_recipes'])[v['recipe']]} (C={v['C']})"
            for c, v in pcc.items()
        )
        + "."
    )
    a("")
    for c in CATEGORIES:
        a(f"* `{c}` ({CATEGORY_KIND[c].replace('_', ' ')}): ESC-50 {', '.join(CATEGORY_MAP[c])}.")
    a("")
    a(
        "Inputs, pooling and use are as in v1: 1024-d BirdNET window embeddings (3 s windows); segments of 2 windows; a category's recording score is its k-th highest segment score with k = max(1, ceil(0.25 x segments)). Code: `backend/thicket/models/qc_head.py` (NumPy only); weights `backend/thicket/models/data/qc_head_v2.npz` with `qc_head_v2.json`. `load_default()` returns v2."
    )
    a("")
    a("## Intended use and out of scope")
    a("")
    a(
        "Unchanged from v1: warnings for likely contamination (rain, wind, thunder, water, engines and machinery, human non-speech sounds, domestic animals) next to BirdNET results, for a person to act on. Not for species identification, weather measurement, speech detection, automatic deletion of recordings, or commercial use. The `bird`, `insect` and `frog` scores are for internal diagnostics only."
    )
    a("")
    a("## Training data")
    a("")
    a(
        f"All 2,000 ESC-50 clips (CC BY-NC 3.0) plus {exp['n_training_rows']['mixtures']} synthetic mixtures made by adding two clips from the same ESC-50 fold at a random signal-to-noise ratio between -10 and +15 dB. **The mixtures are synthetic, not field recordings.**"
    )
    a("")
    a("## Evaluation")
    a("")
    a(
        "ESC-50's 5 official folds; mixtures are built inside each fold, so train and test never share a source recording. Hyperparameters, calibration and thresholds are chosen on training folds only. 95% CIs by bootstrap over source recordings (two-way for mixtures)."
    )
    a("")
    a("Clean ESC-50 test folds (v2, default thresholds):")
    a("")
    a("| Category | Precision | Recall | F1 | Average precision |")
    a("|---|---|---|---|---|")
    for c in CATEGORIES:
        r = cl["per_class"][c]
        a(f"| `{c}` | {ci(r['precision'])} | {ci(r['recall'])} | {ci(r['f1'])} | {ci(r['ap'])} |")
    a(
        f"| **macro** | {ci(cl['macro']['precision'])} | {ci(cl['macro']['recall'])} | {ci(cl['macro']['f1'])} | {ci(cl['macro']['ap'])} |"
    )
    a("")
    d = res["clean"]["diff_v2_minus_v1"]
    a(
        f"* Clean macro AP difference from v1: {ci(d['macro_ap'])}; macro F1 difference: {ci(d['macro_f1'])}."
    )
    a(
        "* Synthetic mixtures, contaminant flagged under the backend rule (v1 then v2): "
        + "; ".join(
            f"{lab} {pc(E['v1'][f'all@{k}']['detected'])} then {pc(E['v2'][f'all@{k}']['detected'])}"
            for k, lab in SNR_KEYS
        )
        + "."
    )
    a(
        f"* False contamination warnings on clean bird, frog and insect clips (backend rule): v1 {pc(ff['v1'])}, v2 {pc(ff['v2'])}."
    )
    a(
        f"* Long synthetic recordings (backend rule): contamination covering half or all of 30 s flagged {100 * pcb['detection_rate']['3']['mean_over_categories']['segment_top25']:.0f}% / {100 * pcb['detection_rate']['6']['mean_over_categories']['segment_top25']:.0f}% of the time; false warnings on clean 30 s / 60 s recordings {100 * pcb['false_flag_rate']['6']['segment_top25']['any_contamination']:.0f}% / {100 * pcb['false_flag_rate']['12']['segment_top25']['any_contamination']:.0f}%."
    )
    a("")
    a("These are ESC-50 and synthetic-mixture numbers, not field accuracy.")
    a("")
    a("## Decision thresholds")
    a("")
    a("| Category | Default (F1) | Strict (precision >= 0.9) |")
    a("|---|---|---|")
    for c in CATEGORIES:
        a(f"| `{c}` | {exp['thresholds_f1'][c]:.3f} | {exp['thresholds_p90'][c]:.3f} |")
    a("")
    a("## Limitations")
    a("")
    for s in limits(res):
        a(f"* {s}")
    a("")
    a("## Ethical and privacy notes")
    a("")
    a(
        "As in v1: `human_nonspeech` can reveal that people were present, so treat it as personal data under the retention policy; a missing flag does not prove a recording is clean; warnings should explain, not blame."
    )
    a("")
    a("## License and provenance")
    a("")
    a(
        "* License: CC BY-NC-SA 4.0 (BirdNET v2.4 embeddings, CC BY-NC-SA 4.0; ESC-50, CC BY-NC 3.0). Non-commercial use only; share alike."
    )
    a(f"* BirdNET weights sha256: `{res['config']['birdnet_sha256']}`.")
    a(f"* Artifact sha256: `{exp['artifact_sha256']}`.")
    a(
        "* Reproduce: `python ml/train/esc50_qc_mix.py all --data <cache dir>` (after the v1 `features` and `evaluate` stages)."
    )
    a("")
    CARD.write_text("\n".join(L))


def write_all(res: dict) -> None:
    if mx.RESULTS_V2A.exists():
        res = dict(res)
        res["_v2a"] = json.loads(mx.RESULTS_V2A.read_text())
    write_report(res)
    written = [REPORT]
    if "export" in res:
        write_card(res)
        written.append(CARD)
    for p in written:
        if chr(0x2014) in p.read_text():
            raise RuntimeError(f"em dash found in {p}")
    print("[v2 report] wrote " + ", ".join(str(p) for p in written))
