/**
 * Demo mode data source (static hosting, no backend). Files live under
 * `${BASE_URL}demo/` and are generated by a separate process:
 *
 *   demo/index.json                      { analyses: DemoEntry[] }
 *   demo/<id>/threshold-0.10.json ... threshold-0.95.json   full Analysis JSON
 *   demo/<id>/spectrogram.png
 *   demo/<id>/audio.mp3
 */
import { ApiError, isAbortError } from '../api/client';
import type { Analysis } from '../api/types';
import { publicBase } from '../config';
import { round2 } from './threshold';

export interface DemoEntry {
  id: string;
  title: string;
  description: string;
  attribution: string;
  license: string;
}

export const DEMO_THRESHOLD_MIN = 0.1;
export const DEMO_THRESHOLD_MAX = 0.95;

export function demoPath(...segments: string[]): string {
  return `${publicBase()}demo/${segments.map(encodeURIComponent).join('/')}`;
}

export function demoThresholdFile(threshold: number): string {
  const clamped = Math.min(DEMO_THRESHOLD_MAX, Math.max(DEMO_THRESHOLD_MIN, threshold));
  const snapped = round2(Math.round(clamped / 0.05) * 0.05);
  return `threshold-${snapped.toFixed(2)}.json`;
}

async function fetchJson(url: string, signal?: AbortSignal): Promise<unknown> {
  let response: Response;
  try {
    response = await fetch(url, { signal, headers: { Accept: 'application/json' } });
  } catch (error) {
    if (isAbortError(error)) throw error;
    throw new ApiError('network', 'The demo data could not be downloaded.');
  }
  if (!response.ok) {
    throw new ApiError(
      response.status === 404 ? 'analysis_not_found' : 'backend_unavailable',
      `The demo file ${url} could not be loaded (${response.status}).`,
      response.status,
    );
  }
  try {
    return await response.json();
  } catch {
    throw new ApiError('invalid_response', 'A demo file is not valid JSON.');
  }
}

function isDemoEntry(value: unknown): value is DemoEntry {
  if (typeof value !== 'object' || value === null) return false;
  const v = value as Record<string, unknown>;
  return typeof v.id === 'string' && typeof v.title === 'string';
}

export async function loadDemoIndex(signal?: AbortSignal): Promise<DemoEntry[]> {
  const body = await fetchJson(demoPath('index.json'), signal);
  const list = (body as { analyses?: unknown })?.analyses;
  if (!Array.isArray(list)) return [];
  return list.filter(isDemoEntry).map((entry) => ({
    id: entry.id,
    title: entry.title,
    description: typeof entry.description === 'string' ? entry.description : '',
    attribution: typeof entry.attribution === 'string' ? entry.attribution : '',
    license: typeof entry.license === 'string' ? entry.license : '',
  }));
}

export async function loadDemoAnalysis(
  id: string,
  threshold: number,
  signal?: AbortSignal,
): Promise<Analysis> {
  const body = (await fetchJson(demoPath(id, demoThresholdFile(threshold)), signal)) as Analysis;
  if (!body || typeof body !== 'object' || typeof body.id !== 'string') {
    throw new ApiError('invalid_response', 'A demo analysis file is incomplete.');
  }
  // Assets are served next to the JSON files, not by an API server.
  return {
    ...body,
    assets: {
      ...body.assets,
      spectrogram_url: demoPath(id, 'spectrogram.png'),
      audio_url: demoPath(id, 'audio.mp3'),
      csv_url: '',
      json_url: '',
    },
  };
}
